
# NOTE: this file is automatically generated

from iommi import *
from iommi.admin import Admin
from iommi.struct import Struct
from django.urls import (
    include,
    path,
)
import pytest
from django.db import models
from tests.helpers import req, user_req, staff_req, show_output
from docs.models import *

pytestmark = pytest.mark.django_db

@pytest.fixture(autouse=True)
def auto_use(big_discography):
    pass

request = req('get')


# language=rst
"""
    
Members
=======

Base class: :doc:`Traversable`

"""
def test_base():
    # language=rst
    """
Internal iommi class that holds members of another class, for example the columns of a `Table` instance.

    """

    # language=rst
    """

Refinable members
-----------------


`extra_params`
^^^^^^^^^^^^^^

    See :ref:`extra_params <extra_params>`


`iommi_style`
^^^^^^^^^^^^^

Type: `str`

    See :ref:`iommi_style <iommi_style>`


Methods
-------

`on_bind`
^^^^^^^^^

    """
