
# NOTE: this file is automatically generated

from iommi import *
from iommi.admin import Admin
from iommi.struct import Struct
from django.urls import (
    include,
    path,
)
import pytest
from django.db import models
from tests.helpers import req, user_req, staff_req, show_output
from docs.models import *

pytestmark = pytest.mark.django_db

@pytest.fixture(autouse=True)
def auto_use(big_discography):
    pass

request = req('get')


# language=rst
"""
    
Style
=====

Base class: `object`

"""
def test_base():
    # language=rst
    """
    """

    # language=rst
    """

Methods
-------

`resolve`
^^^^^^^^^



Calculate the namespaces of additional argument that should be applied
to the given object. If is_root is set to True, assets might also be
added to the namespace.



    """
