
# NOTE: this file is automatically generated

from iommi import *
from iommi.admin import Admin
from iommi.struct import Struct
from django.urls import (
    include,
    path,
)
import pytest
from django.db import models
from tests.helpers import req, user_req, staff_req, show_output
from docs.models import *

pytestmark = pytest.mark.django_db

@pytest.fixture(autouse=True)
def auto_use(big_discography):
    pass

request = req('get')


# language=rst
"""
    
Cell
====

Base class: `CellConfig`

"""
def test_base():
    # language=rst
    """
    """

    # language=rst
    """

Methods
-------

`get_context`
^^^^^^^^^^^^^

`get_request`
^^^^^^^^^^^^^

`iommi_evaluate_parameters`
^^^^^^^^^^^^^^^^^^^^^^^^^^^

`render_cell_contents`
^^^^^^^^^^^^^^^^^^^^^^

`render_formatted`
^^^^^^^^^^^^^^^^^^

    """
