
# NOTE: this file is automatically generated

from iommi import *
from iommi.admin import Admin
from iommi.struct import Struct
from django.urls import (
    include,
    path,
)
import pytest
from django.db import models
from tests.helpers import req, user_req, staff_req, show_output
from docs.models import *

pytestmark = pytest.mark.django_db

@pytest.fixture(autouse=True)
def auto_use(big_discography):
    pass

request = req('get')


# language=rst
"""
    
ColumnHeader
============

Base class: `object`

"""
def test_base():
    # language=rst
    """
Internal class implementing a column header. For configuration options
read the docs for :doc:`HeaderConfig`.

    """

    # language=rst
    """

    """
